services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: dev
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: dev
    ports:
      - '13306:3306'