spring:
  docker:
    compose:
      file: dev-compose.yml

server:
  port: 8000

app:
  parser: DEFAULT
  source:
    fs:
      active: "true"
      # Will use test resources as source folder
      dir: ./src/test/resources/